name: Go Unit Tests

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'client/**'
      - '**.md'
      - 'misc/**'

  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'client/**'
      - '**.md'
      - 'misc/**'

env:
  GO_VERSION: '1.23'

jobs:

  test-unit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true


      - name: Tests
        run: cd go && go test ./...